# Generated by Django 5.0.6 on 2024-05-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility_bed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("district", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hospital_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("city_town", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
