apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-api
  name: backend-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend-api
    spec:
      containers:
      - image: jcharistech/hospitals-api:0.0.1
        name: hospitals-api
        ports:
        - containerPort: 8000
        resources: 
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            memory: 400Mi
status: {}
